import { TOOL_DESCRIPTIONS, type Capability } from './index';
import { SUPPORTED_LANGUAGES } from '../prompt/languages';

export type CatalogLocale = (typeof SUPPORTED_LANGUAGES)[number];
export const CATALOG_LOCALES = SUPPORTED_LANGUAGES;

export type ToolCategory = 'ia-ml' | 'diseno-ui' | 'video-audio' | 'codigo-dev' | 'datos-backend' | 'seguridad' | 'nube-infra' | 'automatizacion' | 'contenido-cms' | 'aprendizaje' | 'productividad-equipo';

export interface LocalizedTool { name: string; description: string; tags: string[]; }
export interface ToolCatalogEntry {
  id: Capability;
  category: ToolCategory;
  route: string;
  external?: boolean;
  related: Capability[];
  consolidates: Capability[];
  i18n: Partial<Record<CatalogLocale, LocalizedTool>>;
}

const CATALOG_META: Record<Capability, { category: ToolCategory; route: string; related: Capability[]; consolidates: Capability[] }> = {
  calculator: { category: 'codigo-dev', route: '/studio', related: [], consolidates: [] },
  web: { category: 'ia-ml', route: '/studio', related: ['reach'], consolidates: [] },
  image: { category: 'ia-ml', route: '/gallery', related: ['video', 'design', 'pngrender'], consolidates: [] },
  video: { category: 'video-audio', route: '/studio', related: ['image', 'music', 'design', 'video_edit'], consolidates: [] },
  music: { category: 'video-audio', route: '/studio', related: ['video', 'content', 'studio'], consolidates: [] },
  design: { category: 'diseno-ui', route: '/studio', related: ['designcompose', 'image', 'video'], consolidates: [] },
  reach: { category: 'ia-ml', route: '/studio', related: ['web'], consolidates: [] },
  skills: { category: 'ia-ml', route: '/dashboard', related: ['g0dm0d3', 'genesis'], consolidates: [] },
  content: { category: 'video-audio', route: '/studio', related: ['music', 'video', 'studio'], consolidates: [] },
  g0dm0d3: { category: 'ia-ml', route: '/studio', related: ['skills'], consolidates: [] },
  topics: { category: 'contenido-cms', route: '/dashboard', related: ['contenido', 'autopub', 'metrics'], consolidates: [] },
  present: { category: 'contenido-cms', route: '/dashboard', related: ['publications', 'contenido', 'autopub'], consolidates: [] },
  publish: { category: 'contenido-cms', route: '/dashboard', related: ['publications', 'autopub'], consolidates: [] },
  publications: { category: 'contenido-cms', route: '/dashboard', related: ['autopub', 'present', 'contenido', 'metrics'], consolidates: [] },
  contenido: { category: 'contenido-cms', route: '/dashboard', related: ['present', 'publications', 'topics', 'autopub'], consolidates: [] },
  metrics: { category: 'contenido-cms', route: '/metrics', related: ['publications', 'autopub', 'growth'], consolidates: [] },
  memory: { category: 'datos-backend', route: '/dashboard', related: ['semantic_memory', 'qdrant_memory', 'brainpage', 'autolearn'], consolidates: [] },
  diagram: { category: 'diseno-ui', route: '/studio', related: ['design', 'studio'], consolidates: [] },
  video_edit: { category: 'video-audio', route: '/studio', related: ['video', 'screenflow', 'vfx', 'motion'], consolidates: [] },
  screenflow: { category: 'video-audio', route: '/studio', related: ['video_edit', 'video', 'studio'], consolidates: [] },
  cloud: { category: 'nube-infra', route: '/cloud', related: ['vault', 'netwatch'], consolidates: [] },
  harness: { category: 'automatizacion', route: '/dashboard', related: ['genesis', 'cerebro'], consolidates: [] },
  growth: { category: 'productividad-equipo', route: '/dashboard', related: ['metrics', 'cerebro', 'autopub'], consolidates: [] },
  vfx: { category: 'video-audio', route: '/studio', related: ['codevfx', 'video_edit', 'video'], consolidates: [] },
  codevfx: { category: 'video-audio', route: '/studio', related: ['vfx', 'designcompose', 'generative'], consolidates: [] },
  recordly: { category: 'video-audio', route: '/studio', related: ['screenflow', 'video_edit'], consolidates: [] },
  cerebro: { category: 'productividad-equipo', route: '/dashboard', related: ['autopub', 'genesis', 'growth'], consolidates: [] },
  travel: { category: 'video-audio', route: '/studio', related: ['video', 'image', 'generative'], consolidates: [] },
  generative: { category: 'video-audio', route: '/studio', related: ['pngrender', 'procvid', 'physics2d', 'creativo', 'sdf'], consolidates: [] },
  research: { category: 'aprendizaje', route: '/studio', related: ['pdfsearch', 'enlaces', 'kgraph'], consolidates: [] },
  enlaces: { category: 'aprendizaje', route: '/dashboard', related: ['pdfsearch', 'research', 'libros'], consolidates: [] },
  libros: { category: 'aprendizaje', route: '/ebooks', related: ['enlaces', 'pdfsearch'], consolidates: [] },
  sdf: { category: 'codigo-dev', route: '/studio', related: ['geometry', 'geom', 'pngrender'], consolidates: [] },
  geom: { category: 'codigo-dev', route: '/studio', related: ['geometry', 'cadgeo', 'pngrender', 'sdf'], consolidates: [] },
  videoqa: { category: 'codigo-dev', route: '/studio', related: ['imaging', 'motion'], consolidates: [] },
  motion: { category: 'codigo-dev', route: '/studio', related: ['videoqa', 'imaging', 'video_edit'], consolidates: [] },
  replica: { category: 'codigo-dev', route: '/studio', related: ['videoqa', 'motion', 'generative'], consolidates: [] },
  imaging: { category: 'codigo-dev', route: '/studio', related: ['videoqa', 'motion', 'pngrender'], consolidates: [] },
  creativo: { category: 'video-audio', route: '/studio', related: ['physics2d', 'generative'], consolidates: [] },
  semantic_memory: { category: 'aprendizaje', route: '/dashboard', related: ['memory', 'qdrant_memory', 'brainpage'], consolidates: [] },
  autolearn: { category: 'aprendizaje', route: '/dashboard', related: ['learnModels', 'genesis', 'kgraph'], consolidates: [] },
  genesis: { category: 'automatizacion', route: '/dashboard', related: ['cerebro', 'autolearn', 'harness'], consolidates: [] },
  vault: { category: 'datos-backend', route: '/cloud', related: ['cloud', 'kgraph', 'pdfsearch'], consolidates: [] },
  pdfsearch: { category: 'aprendizaje', route: '/dashboard', related: ['enlaces', 'research', 'vault'], consolidates: [] },
  qdrant_memory: { category: 'aprendizaje', route: '/dashboard', related: ['semantic_memory', 'memory', 'brainpage'], consolidates: [] },
  kgraph: { category: 'datos-backend', route: '/dashboard', related: ['brainpage', 'vault', 'research'], consolidates: [] },
  brainpage: { category: 'aprendizaje', route: '/dashboard', related: ['memory', 'semantic_memory', 'kgraph'], consolidates: [] },
  autopub: { category: 'automatizacion', route: '/dashboard', related: ['publications', 'present', 'contenido', 'topics', 'cerebro'], consolidates: [] },
  security: { category: 'seguridad', route: '/dashboard', related: ['codequality', 'deps'], consolidates: ['codequality', 'deps'] },
  codequality: { category: 'seguridad', route: '/dashboard', related: ['security', 'deps'], consolidates: ['security', 'deps'] },
  deps: { category: 'seguridad', route: '/dashboard', related: ['security', 'codequality'], consolidates: ['security', 'codequality'] },
  geometry: { category: 'codigo-dev', route: '/studio', related: ['geom', 'cadgeo', 'pngrender', 'sdf'], consolidates: ['geom'] },
  pngrender: { category: 'codigo-dev', route: '/studio', related: ['geometry', 'procvid', 'generative'], consolidates: [] },
  procvid: { category: 'video-audio', route: '/studio', related: ['pngrender', 'generative', 'physics2d'], consolidates: [] },
  physics2d: { category: 'codigo-dev', route: '/studio', related: ['creativo', 'generative', 'procvid'], consolidates: [] },
  cadgeo: { category: 'codigo-dev', route: '/studio', related: ['geometry', 'geom', 'pngrender'], consolidates: ['geometry'] },
  evo: { category: 'codigo-dev', route: '/studio', related: ['evolution', 'generative'], consolidates: [] },
  evolution: { category: 'codigo-dev', route: '/studio', related: ['evo', 'generative'], consolidates: [] },
  studio: { category: 'video-audio', route: '/studio', related: ['video', 'image', 'music', 'content'], consolidates: [] },
  netwatch: { category: 'nube-infra', route: '/dashboard', related: ['cerebro'], consolidates: [] },
  designcompose: { category: 'diseno-ui', route: '/studio', related: ['design', 'geometry', 'pngrender'], consolidates: [] },
  learnModels: { category: 'aprendizaje', route: '/dashboard', related: ['autolearn', 'semantic_memory'], consolidates: [] },
};


export const ES: Partial<Record<Capability, LocalizedTool>> = {
  calculator: { name: 'Calculadora', description: 'Evalua una expresion matematica de forma segura (solo matematicas).', tags: ['matematicas','calculo'] },
  web: { name: 'Web', description: 'Lee el texto y metadatos de una pagina publica (web o publicacion social no privada). Sin claves.', tags: ['web','lectura'] },
  image: { name: 'Imagen', description: 'Genera una imagen fotorrealista desde un texto con un modelo gratuito sin claves. Devuelve una URL.', tags: ['imagen','generacion'] },
  video: { name: 'Video', description: 'Produce un guion grafico de video (secuencia de fotogramas) desde un texto. Sin claves; video real si hay proveedor.', tags: ['video','guion'] },
  music: { name: 'Musica', description: 'Compone una pieza musical original desde un texto. Sin claves; audio real si hay proveedor.', tags: ['musica','composicion'] },
  design: { name: 'Diseno UI', description: 'Genera una pantalla UI de alta fidelidad desde un texto con Google Stitch (Google Labs gratis).', tags: ['diseno','ui'] },
  reach: { name: 'Alcance web', description: 'Acceso a internet en tiempo real: lee paginas, busca, busca en GitHub, parsea RSS y metadatos de YouTube.', tags: ['web','busqueda'] },
  skills: { name: 'Habilidades', description: 'Ejecuta un paso del pipeline de desarrollo de agentes: plan, build, test, review, ship, simplify.', tags: ['agentes','pipeline'] },
  content: { name: 'Recursos de contenido', description: 'Assets libres para video y audio: musica y efectos (Tunetank) y stock (mixkit).', tags: ['contenido','assets'] },
  g0dm0d3: { name: 'G0DM0D3', description: 'Evaluacion y pruebas estilo G0DM0D3: perturbacion de entrada, muestreo adaptativo y evaluacion multiangulo.', tags: ['evaluacion','pruebas'] },
  topics: { name: 'Temas', description: 'Motor de ideas de contenido (AutoPub F1): briefs priorizados desde RSS y DuckDuckGo.', tags: ['contenido','ideas'] },
  present: { name: 'Presentacion', description: 'Constructor de publicaciones (AutoPub F3): paquete por canal con captions, hashtags, visuales y horario.', tags: ['publicacion','paquete'] },
  publish: { name: 'Publicar', description: 'Adaptadores de distribucion (AutoPub F4): YouTube, TikTok, X, Meta, Telegram, Discord, Slack, LinkedIn.', tags: ['distribucion','canales'] },
  publications: { name: 'Cola de publicaciones', description: 'Gestion de la cola de publicacion (AutoPub F4): crear, aprobar, rechazar y publicar lo programado.', tags: ['cola','publicacion'] },
  contenido: { name: 'Contenido', description: 'Enrutador de contenido (AutoPub F2): de brief a post o guion de video con manifest.json.', tags: ['contenido','guion'] },
  metrics: { name: 'Metricas', description: 'KPIs por canal y senales de feedback para cerrar el bucle de contenido.', tags: ['metricas','analytics'] },
  memory: { name: 'Memoria', description: 'Sistema de archivos de memoria de agente: recuerda y lee lo que el usuario cuenta entre sesiones.', tags: ['memoria','persistencia'] },
  diagram: { name: 'Diagramas', description: 'Diagramas editoriales autocontenidos (timeline, data-flow, architecture, loop) en Dark Obsidian.', tags: ['diagrama','visualizacion'] },
  video_edit: { name: 'Edicion de video', description: 'Pipeline de edicion: transcripcion, EDL, render ffmpeg y autoevaluacion determinista.', tags: ['video','edicion'] },
  screenflow: { name: 'ScreenFlow', description: 'Automatizacion de grabacion de pantalla: plan, captura, edicion y publicacion local.', tags: ['pantalla','automatizacion'] },
  cloud: { name: 'Nube', description: 'Almacenamiento en la nube del proyecto: local o Cloudflare R2, con validacion de rutas y tamanos.', tags: ['nube','almacenamiento'] },
  harness: { name: 'Harness', description: 'Runtime de plugins para agentes: arranca, ejecuta y apaga un arbol de plugins determinista.', tags: ['plugins','runtime'] },
  growth: { name: 'Crecimiento', description: 'Motor de crecimiento de canal: perfil, experimentos A/B y playbook que acumula victorias.', tags: ['crecimiento','youtube'] },
  vfx: { name: 'VFX', description: 'Planificador de postproduccion (reframe, upscale, LUT, rotoscopia, B-roll) determinista.', tags: ['vfx','postproduccion'] },
  codevfx: { name: 'CodeVFX', description: 'Efectos visuales 100 por ciento codigo (sin assets): fuego, hielo, relampago, con GLSL y fisica.', tags: ['efectos','codigo'] },
  recordly: { name: 'Recordly', description: 'Planificador de ScreenFlow Studio: auto-zoom, presets de cursor, burbuja webcam y export MP4.', tags: ['screenflow','demo'] },
  cerebro: { name: 'Cerebro', description: 'Cerebro autonomo de UltraIa: aprende, crea, publica y reporta en un ciclo programado.', tags: ['autonomo','ciclo'] },
  travel: { name: 'Video de viajes', description: 'Motor de video de viajes: plan 9:16 desde un destino con narracion bilingue y render ffmpeg.', tags: ['viajes','video'] },
  generative: { name: 'Generativo', description: 'Motor de medios procedurales 100 por ciento codigo: imagenes, video y audio desde matematicas.', tags: ['procedural','media'] },
  research: { name: 'Investigacion', description: 'Motor de investigacion: arXiv, GitHub, web en vivo y extraccion de URLs como texto.', tags: ['investigacion','conocimiento'] },
  enlaces: { name: 'Enlaces', description: 'Curaduria de enlaces: descarga y compromete fuentes compartidas en el proyecto.', tags: ['enlaces','fuentes'] },
  libros: { name: 'Libros', description: 'Catalogo de 115 libros y tutoriales de programacion gratis en espanol.', tags: ['libros','aprendizaje'] },
  sdf: { name: 'SDF', description: 'Campos de distancia firmados y ray marching 100 por ciento codigo: escenas 3D y GLSL.', tags: ['3d','raymarching'] },
  geom: { name: 'Geometria', description: 'Biblioteca de geometria y matematicas: vectores, matrices, mallas y SVG.', tags: ['geometria','matematicas'] },
  videoqa: { name: 'VideoQA', description: 'Metricas de calidad de video: PSNR, SSIM, flujo optico y veredicto PASS o FAIL.', tags: ['calidad','video'] },
  motion: { name: 'Motion', description: 'Analisis de movimiento de video: campo de flujo optico y descomposicion camara o escena.', tags: ['movimiento','analisis'] },
  replica: { name: 'Replica', description: 'Orquestador analisis-por-sintesis: replica un objetivo generandolo y comparando.', tags: ['replica','sintesis'] },
  imaging: { name: 'Imaging', description: 'Kernels de procesamiento de imagenes en TypeScript puro: filtros, bordes, flujo optico.', tags: ['imagen','procesamiento'] },
  creativo: { name: 'Creativo', description: 'Motor de fisica creativa 100 por ciento codigo: particulas 2D, sonido y canvas.', tags: ['fisica','creativo'] },
  semantic_memory: { name: 'Memoria semantica', description: 'Recuperacion semantica sobre conocimiento verificado con hashing y coseno.', tags: ['memoria','semantica'] },
  autolearn: { name: 'Autoaprendizaje', description: 'Agente de autoprogramacion: detecta vacios y genera el plan de mejora.', tags: ['aprendizaje','automatizacion'] },
  genesis: { name: 'Genesis', description: 'Motor de ingenieria autonoma: valida manifiesto y elige la siguiente accion.', tags: ['ingenieria','autonomo'] },
  vault: { name: 'Boveda', description: 'Repositorio propio: guarda datos, archivos, creaciones y pruebas del proyecto.', tags: ['boveda','almacenamiento'] },
  pdfsearch: { name: 'PDF Search', description: 'Busqueda de PDF: OpenAlex y DuckDuckGo filetype:pdf llevados a la boveda.', tags: ['pdf','busqueda'] },
  qdrant_memory: { name: 'Memoria Qdrant', description: 'Memoria persistente externa en Qdrant para el corpus de verdad verificada.', tags: ['memoria','persistencia'] },
  kgraph: { name: 'Knowledge Graph', description: 'Constructor de grafo de conocimiento desde codigo y documentos.', tags: ['grafo','conocimiento'] },
  brainpage: { name: 'BrainPage', description: 'Memoria Markdown persistente con linea de tiempo de evidencia.', tags: ['memoria','markdown'] },
  autopub: { name: 'AutoPub', description: 'Fabrica de contenido autonoma: ejecuta el ciclo F1-F4 de forma autonoma.', tags: ['autopub','contenido'] },
  security: { name: 'Seguridad', description: 'Escaner de secretos y configuraciones de riesgo en texto o repo.', tags: ['seguridad','secretos'] },
  codequality: { name: 'Calidad de codigo', description: 'Linter de code smells comunes: debugger, eval, any, console.log.', tags: ['calidad','linter'] },
  deps: { name: 'Dependencias', description: 'Auditoria de vulnerabilidades (SCA) con npm audit.', tags: ['dependencias','cve'] },
  geometry: { name: 'Geometria parametrica', description: 'Geometria procedural (superformula de Gielis): mallas y export glTF o OBJ.', tags: ['geometria','glTF'] },
  pngrender: { name: 'PNG Render', description: 'Renderizador PNG en TypeScript puro: imagenes desde funciones matematicas.', tags: ['png','render'] },
  procvid: { name: 'Procedural Video', description: 'Video procedural determinista: animaciones y ensamblaje ffmpeg o GIF.', tags: ['video','procedural'] },
  physics2d: { name: 'Fisica 2D', description: 'Fisica 2D determinista (Verlet y cuerpos rigidos) con canvas.', tags: ['fisica','2d'] },
  cadgeo: { name: 'CAD Geometry', description: 'Toolkit de geometria computacional: Delaunay, Voronoi, BVH, B-spline.', tags: ['geometria','cad'] },
  evo: { name: 'Evolutivo', description: 'Algoritmo genetico determinista reproducible (xorshift32).', tags: ['genetico','optimizacion'] },
  evolution: { name: 'Evolucion', description: 'Motor de evolucion de artefactos con memoria persistente.', tags: ['evolucion','artefactos'] },
  studio: { name: 'Studio', description: 'Hub de medios: guarda, reproduce y deriva assets generados.', tags: ['studio','media'] },
  netwatch: { name: 'NetWatch', description: 'Vigilante de red WiFi: monitorea y reconecta la conexion.', tags: ['red','wifi'] },
  designcompose: { name: 'Design Compose', description: 'Composicion 2D o 3D determinista y sin claves desde matematicas.', tags: ['diseno','composicion'] },
  learnModels: { name: 'Modelos de aprendizaje', description: 'Aprendizaje programado: pensamientos, compresion de memoria y meta-razonamiento.', tags: ['aprendizaje','meta'] },
};

export const PT: Partial<Record<Capability, LocalizedTool>> = {
  calculator: { name: 'Calculadora', description: 'Avalia uma expressao matematica de forma segura (apenas matematica).', tags: ['matematica','calculo'] },
  web: { name: 'Web', description: 'Le o texto e os metadados de uma pagina publica (web ou publicacao social nao privada). Sem chaves.', tags: ['web','leitura'] },
  image: { name: 'Imagem', description: 'Gera uma imagem fotorrealista a partir de um texto com um modelo gratuito sem chaves. Retorna uma URL.', tags: ['imagem','geracao'] },
  video: { name: 'Video', description: 'Produz um roteiro de video (sequencia de quadros) a partir de um texto. Sem chaves; video real se houver provedor.', tags: ['video','roteiro'] },
  music: { name: 'Musica', description: 'Compoe uma peca musical original a partir de um texto. Sem chaves; audio real se houver provedor.', tags: ['musica','composicao'] },
  design: { name: 'Design UI', description: 'Gera uma tela de UI de alta fidelidade a partir de um texto com o Google Stitch (Google Labs gratis).', tags: ['design','ui'] },
  reach: { name: 'Alcance web', description: 'Acesso a internet em tempo real: le paginas, busca, busca no GitHub, analisa RSS e metadados do YouTube.', tags: ['web','busca'] },
  skills: { name: 'Habilidades', description: 'Executa uma etapa do pipeline de desenvolvimento de agentes: plan, build, test, review, ship, simplify.', tags: ['agentes','pipeline'] },
  content: { name: 'Recursos de conteudo', description: 'Assets livres para video e audio: musica e efeitos (Tunetank) e banco (mixkit).', tags: ['conteudo','assets'] },
  g0dm0d3: { name: 'G0DM0D3', description: 'Avaliacao e testes estilo G0DM0D3: perturbacao de entrada, amostragem adaptativa e avaliacao multiangulo.', tags: ['avaliacao','testes'] },
  topics: { name: 'Temas', description: 'Motor de ideias de conteudo (AutoPub F1): briefs priorizados a partir de RSS e DuckDuckGo.', tags: ['conteudo','ideias'] },
  present: { name: 'Apresentacao', description: 'Construtor de publicacoes (AutoPub F3): pacote por canal com captions, hashtags, visuais e horario.', tags: ['publicacao','pacote'] },
  publish: { name: 'Publicar', description: 'Adaptadores de distribuicao (AutoPub F4): YouTube, TikTok, X, Meta, Telegram, Discord, Slack, LinkedIn.', tags: ['distribuicao','canais'] },
  publications: { name: 'Fila de publicacoes', description: 'Gestao da fila de publicacao (AutoPub F4): criar, aprovar, rejeitar e publicar o programado.', tags: ['fila','publicacao'] },
  contenido: { name: 'Conteudo', description: 'Roteirizador de conteudo (AutoPub F2): de brief a post ou roteiro de video com manifest.json.', tags: ['conteudo','roteiro'] },
  metrics: { name: 'Metricas', description: 'KPIs por canal e sinais de feedback para fechar o laco de conteudo.', tags: ['metricas','analytics'] },
  memory: { name: 'Memoria', description: 'Sistema de arquivos de memoria do agente: lembra e le o que o usuario conta entre sessoes.', tags: ['memoria','persistencia'] },
  diagram: { name: 'Diagramas', description: 'Diagramas editoriais autocontidos (timeline, data-flow, architecture, loop) em Dark Obsidian.', tags: ['diagrama','visualizacao'] },
  video_edit: { name: 'Edicao de video', description: 'Pipeline de edicao: transcricao, EDL, render ffmpeg e autoavaliacao deterministica.', tags: ['video','edicao'] },
  screenflow: { name: 'ScreenFlow', description: 'Automatizacao de gravacao de tela: plano, captura, edicao e publicacao local.', tags: ['tela','automatizacao'] },
  cloud: { name: 'Nuvem', description: 'Armazenamento em nuvem do projeto: local ou Cloudflare R2, com validacao de rotas e tamanhos.', tags: ['nuvem','armazenamento'] },
  harness: { name: 'Harness', description: 'Runtime de plugins para agentes: inicia, executa e encerra uma arvore de plugins deterministica.', tags: ['plugins','runtime'] },
  growth: { name: 'Crescimento', description: 'Motor de crescimento de canal: perfil, experimentos A/B e playbook que acumula vitorias.', tags: ['crescimento','youtube'] },
  vfx: { name: 'VFX', description: 'Planejador de pos-producao (reframe, upscale, LUT, rotoscopia, B-roll) deterministico.', tags: ['vfx','posproducao'] },
  codevfx: { name: 'CodeVFX', description: 'Efeitos visuais 100 por cento codigo (sem assets): fogo, gelo, relampago, com GLSL e fisica.', tags: ['efeitos','codigo'] },
  recordly: { name: 'Recordly', description: 'Planejador de ScreenFlow Studio: auto-zoom, predefinicoes de cursor, bolha webcam e export MP4.', tags: ['screenflow','demo'] },
  cerebro: { name: 'Cerebro', description: 'Cerebro autonomo da UltraIa: aprende, cria, publica e reporta em um ciclo programado.', tags: ['autonomo','ciclo'] },
  travel: { name: 'Video de viagens', description: 'Motor de video de viagens: plano 9:16 a partir de um destino com narracao bilinguie e render ffmpeg.', tags: ['viagens','video'] },
  generative: { name: 'Generativo', description: 'Motor de midia procedural 100 por cento codigo: imagens, video e audio a partir de matematica.', tags: ['procedural','midia'] },
  research: { name: 'Pesquisa', description: 'Motor de pesquisa: arXiv, GitHub, web ao vivo e extracao de URLs como texto.', tags: ['pesquisa','conhecimento'] },
  enlaces: { name: 'Ligacoes', description: 'Curadoria de ligacoes: baixa e envolve fontes compartilhadas no projeto.', tags: ['ligacoes','fontes'] },
  libros: { name: 'Livros', description: 'Catalogo de 115 livros e tutoriais de programacao gratuitos em espanhol.', tags: ['livros','aprendizagem'] },
  sdf: { name: 'SDF', description: 'Campos de distancia assinados e ray marching 100 por cento codigo: cenas 3D e GLSL.', tags: ['3d','raymarching'] },
  geom: { name: 'Geometria', description: 'Biblioteca de geometria e matematica: vetores, matrizes, malhas e SVG.', tags: ['geometria','matematica'] },
  videoqa: { name: 'VideoQA', description: 'Metricas de qualidade de video: PSNR, SSIM, fluxo optico e veredito PASS ou FAIL.', tags: ['qualidade','video'] },
  motion: { name: 'Motion', description: 'Analise de movimento de video: campo de fluxo optico e decomposicao camera ou cena.', tags: ['movimento','analise'] },
  replica: { name: 'Replica', description: 'Orquestrador analise-por-sintese: replica um objetivo gerando-o e comparando.', tags: ['replica','sintese'] },
  imaging: { name: 'Imaging', description: 'Kernels de processamento de imagem em TypeScript puro: filtros, bordas, fluxo optico.', tags: ['imagem','processamento'] },
  creativo: { name: 'Criativo', description: 'Motor de fisica criativa 100 por cento codigo: particulas 2D, som e canvas.', tags: ['fisica','criativo'] },
  semantic_memory: { name: 'Memoria semantica', description: 'Recuperacao semantica sobre conhecimento verificado com hashing e cosseno.', tags: ['memoria','semantica'] },
  autolearn: { name: 'Autoaprendizagem', description: 'Agente de autoprogramacao: detecta lacunas e gera o plano de melhoria.', tags: ['aprendizagem','automatizacao'] },
  genesis: { name: 'Genesis', description: 'Motor de engenharia autonoma: valida manifesto e escolhe a proxima acao.', tags: ['engenharia','autonomo'] },
  vault: { name: 'Cofre', description: 'Repositorio proprio: guarda dados, arquivos, criacoes e provas do projeto.', tags: ['cofre','armazenamento'] },
  pdfsearch: { name: 'PDF Search', description: 'Busca de PDF: OpenAlex e DuckDuckGo filetype:pdf levados ao cofre.', tags: ['pdf','busca'] },
  qdrant_memory: { name: 'Memoria Qdrant', description: 'Memoria persistente externa em Qdrant para o corpus de verdade verificada.', tags: ['memoria','persistencia'] },
  kgraph: { name: 'Knowledge Graph', description: 'Construtor de grafo de conhecimento a partir de codigo e documentos.', tags: ['grafo','conhecimento'] },
  brainpage: { name: 'BrainPage', description: 'Memoria Markdown persistente com linha do tempo de evidencia.', tags: ['memoria','markdown'] },
  autopub: { name: 'AutoPub', description: 'Fabrica de conteudo autonoma: executa o ciclo F1-F4 de forma autonoma.', tags: ['autopub','conteudo'] },
  security: { name: 'Seguranca', description: 'Verificador de segredos e configuracoes de risco em texto ou repo.', tags: ['seguranca','segredos'] },
  codequality: { name: 'Qualidade de codigo', description: 'Linter de code smells comuns: debugger, eval, any, console.log.', tags: ['qualidade','linter'] },
  deps: { name: 'Dependencias', description: 'Auditoria de vulnerabilidades (SCA) com npm audit.', tags: ['dependencias','cve'] },
  geometry: { name: 'Geometria parametrica', description: 'Geometria procedural (superformula de Gielis): malhas e export glTF ou OBJ.', tags: ['geometria','glTF'] },
  pngrender: { name: 'PNG Render', description: 'Renderizador PNG em TypeScript puro: imagens a partir de funcoes matematicas.', tags: ['png','render'] },
  procvid: { name: 'Procedural Video', description: 'Video procedural deterministico: animacoes e montagem ffmpeg ou GIF.', tags: ['video','procedural'] },
  physics2d: { name: 'Fisica 2D', description: 'Fisica 2D deterministica (Verlet e corpos rigidos) com canvas.', tags: ['fisica','2d'] },
  cadgeo: { name: 'CAD Geometry', description: 'Toolkit de geometria computacional: Delaunay, Voronoi, BVH, B-spline.', tags: ['geometria','cad'] },
  evo: { name: 'Evolutivo', description: 'Algoritmo genetico deterministico reproduzivel (xorshift32).', tags: ['genetico','otimizacao'] },
  evolution: { name: 'Evolucao', description: 'Motor de evolucao de artefatos com memoria persistente.', tags: ['evolucao','artefatos'] },
  studio: { name: 'Studio', description: 'Hub de midia: salva, reproduz e deriva assets gerados.', tags: ['studio','midia'] },
  netwatch: { name: 'NetWatch', description: 'Vigilante de rede WiFi: monitora e reconecta a conexao.', tags: ['rede','wifi'] },
  designcompose: { name: 'Design Compose', description: 'Composicao 2D ou 3D deterministica e sem chaves a partir de matematica.', tags: ['design','composicao'] },
  learnModels: { name: 'Modelos de aprendizagem', description: 'Aprendizagem programada: pensamentos, compressao de memoria e meta-raciocinio.', tags: ['aprendizagem','meta'] },
};
export const IT: Partial<Record<Capability, LocalizedTool>> = {
  calculator: { name: 'Calcolatrice', description: 'Valuta un espressione matematica in modo sicuro (solo matematica).', tags: ['matematica','calcolo'] },
  web: { name: 'Web', description: 'Legge il testo e i metadati di una pagina pubblica (web o pubblicazione social non privata). Senza chiavi.', tags: ['web','lettura'] },
  image: { name: 'Immagine', description: 'Genera un immagine fotorealistica da un testo con un modello gratuito senza chiavi. Restituisce un URL.', tags: ['immagine','generazione'] },
  video: { name: 'Video', description: 'Produce uno storyboard video (sequenza di fotogrammi) da un testo. Senza chiavi; video reale se c\'e un provider.', tags: ['video','storyboard'] },
  music: { name: 'Musica', description: 'Componi un pezzo musicale originale da un testo. Senza chiavi; audio reale se c\'e un provider.', tags: ['musica','composizione'] },
  design: { name: 'Design UI', description: 'Genera una schermata UI ad alta fedelta da un testo con Google Stitch (Google Labs gratis).', tags: ['design','ui'] },
  reach: { name: 'Portata web', description: 'Accesso a internet in tempo reale: leggi pagine, cerca, cerca su GitHub, analizza RSS e metadati di YouTube.', tags: ['web','ricerca'] },
  skills: { name: 'Abilita', description: 'Esegue una fase della pipeline di sviluppo agenti: plan, build, test, review, ship, simplify.', tags: ['agenti','pipeline'] },
  content: { name: 'Risorse di contenuto', description: 'Asset gratuiti per video e audio: musica ed effetti (Tunetank) e stock (mixkit).', tags: ['contenuto','asset'] },
  g0dm0d3: { name: 'G0DM0D3', description: 'Valutazione e test stile G0DM0D3: perturbazione di input, campionamento adattivo e valutazione multiangolo.', tags: ['valutazione','test'] },
  topics: { name: 'Argomenti', description: 'Motore di idee per i contenuti (AutoPub F1): brief priorizzati da RSS e DuckDuckGo.', tags: ['contenuto','idee'] },
  present: { name: 'Presentazione', description: 'Costruttore di pubblicazioni (AutoPub F3): pacchetto per canale con caption, hashtag, visual e orario.', tags: ['pubblicazione','pacchetto'] },
  publish: { name: 'Pubblica', description: 'Adattatori di distribuzione (AutoPub F4): YouTube, TikTok, X, Meta, Telegram, Discord, Slack, LinkedIn.', tags: ['distribuzione','canali'] },
  publications: { name: 'Coda di pubblicazioni', description: 'Gestione della coda di pubblicazione (AutoPub F4): crea, approva, rifiuta e pubblica quanto e programmato.', tags: ['coda','pubblicazione'] },
  contenido: { name: 'Contenuto', description: 'Router di contenuto (AutoPub F2): da brief a post o storyboard video con manifest.json.', tags: ['contenuto','storyboard'] },
  metrics: { name: 'Metriche', description: 'KPI per canale e segnali di feedback per chiudere il ciclo dei contenuti.', tags: ['metriche','analytics'] },
  memory: { name: 'Memoria', description: 'Sistema di archiviazione della memoria dell\'agente: ricorda e legge cio che l\'utente racconta tra le sessioni.', tags: ['memoria','persistenza'] },
  diagram: { name: 'Diagrammi', description: 'Diagrammi editoriali autonomi (timeline, data-flow, architecture, loop) in Dark Obsidian.', tags: ['diagramma','visualizzazione'] },
  video_edit: { name: 'Montaggio video', description: 'Pipeline di montaggio: trascrizione, EDL, render ffmpeg e autovalutazione deterministica.', tags: ['video','montaggio'] },
  screenflow: { name: 'ScreenFlow', description: 'Automazione della registrazione dello schermo: piano, cattura, montaggio e pubblicazione locale.', tags: ['schermo','automazione'] },
  cloud: { name: 'Cloud', description: 'Archiviazione cloud del progetto: locale o Cloudflare R2, con validazione dei percorsi e delle dimensioni.', tags: ['cloud','archiviazione'] },
  harness: { name: 'Harness', description: 'Runtime di plugin per agenti: avvia, esegui e arresta un albero di plugin deterministico.', tags: ['plugin','runtime'] },
  growth: { name: 'Crescita', description: 'Motore di crescita del canale: profilo, esperimenti A/B e playbook che accumula vittorie.', tags: ['crescita','youtube'] },
  vfx: { name: 'VFX', description: 'Pianificatore di post-produzione (reframe, upscale, LUT, rotoscopia, B-roll) deterministico.', tags: ['vfx','postproduzione'] },
  codevfx: { name: 'CodeVFX', description: 'Effetti visivi 100 percento codice (senza asset): fuoco, ghiaccio, fulmine, con GLSL e fisica.', tags: ['effetti','codice'] },
  recordly: { name: 'Recordly', description: 'Pianificatore di ScreenFlow Studio: auto-zoom, preset del cursore, bolla webcam ed export MP4.', tags: ['screenflow','demo'] },
  cerebro: { name: 'Cerebro', description: 'Cervello autonomo di UltraIa: impara, crea, pubblica e riporta in un ciclo programmato.', tags: ['autonomo','ciclo'] },
  travel: { name: 'Video di viaggi', description: 'Motore di video di viaggi: piano 9:16 da una destinazione con narrazione bilingue e render ffmpeg.', tags: ['viaggi','video'] },
  generative: { name: 'Generativo', description: 'Motore di media procedurale 100 percento codice: immagini, video e audio da matematica.', tags: ['procedurale','media'] },
  research: { name: 'Ricerca', description: 'Motore di ricerca: arXiv, GitHub, web in tempo reale ed estrazione di URL come testo.', tags: ['ricerca','conoscenza'] },
  enlaces: { name: 'Collegamenti', description: 'Curazione di collegamenti: scarica e coinvolge fonti condivise nel progetto.', tags: ['collegamenti','fonti'] },
  libros: { name: 'Libri', description: 'Catalogo di 115 libri e tutorial di programmazione gratuiti in spagnolo.', tags: ['libri','apprendimento'] },
  sdf: { name: 'SDF', description: 'Campi di distanza firmati e ray marching 100 percento codice: scene 3D e GLSL.', tags: ['3d','raymarching'] },
  geom: { name: 'Geometria', description: 'Libreria di geometria e matematica: vettori, matrici, mesh e SVG.', tags: ['geometria','matematica'] },
  videoqa: { name: 'VideoQA', description: 'Metriche di qualita video: PSNR, SSIM, flusso ottico e verdetto PASS o FAIL.', tags: ['qualita','video'] },
  motion: { name: 'Motion', description: 'Analisi del movimento video: campo di flusso ottico e decomposizione telecamera o scena.', tags: ['movimento','analisi'] },
  replica: { name: 'Replica', description: 'Orchestratore analisi-per-sintesi: replica un obiettivo generandolo e confrontandolo.', tags: ['replica','sintesi'] },
  imaging: { name: 'Imaging', description: 'Kernel di elaborazione immagini in TypeScript puro: filtri, bordi, flusso ottico.', tags: ['immagine','elaborazione'] },
  creativo: { name: 'Creativo', description: 'Motore di fisica creativa 100 percento codice: particelle 2D, suono e canvas.', tags: ['fisica','creativo'] },
  semantic_memory: { name: 'Memoria semantica', description: 'Recupero semantico su conoscenza verificata con hashing e coseno.', tags: ['memoria','semantica'] },
  autolearn: { name: 'Autoapprendimento', description: 'Agente di autoprogrammazione: rileva lacune e genera il piano di miglioramento.', tags: ['apprendimento','automazione'] },
  genesis: { name: 'Genesis', description: 'Motore di ingegneria autonoma: convalida il manifesto e sceglie la prossima azione.', tags: ['ingegneria','autonomo'] },
  vault: { name: 'Cassaforte', description: 'Repository proprio: conserva dati, file, creazioni e prove del progetto.', tags: ['cassaforte','archiviazione'] },
  pdfsearch: { name: 'PDF Search', description: 'Ricerca di PDF: OpenAlex e DuckDuckGo filetype:pdf portati nel repository.', tags: ['pdf','ricerca'] },
  qdrant_memory: { name: 'Memoria Qdrant', description: 'Memoria persistente esterna in Qdrant per il corpus di verita verificata.', tags: ['memoria','persistenza'] },
  kgraph: { name: 'Knowledge Graph', description: 'Costruttore di grafo della conoscenza da codice e documenti.', tags: ['grafo','conoscenza'] },
  brainpage: { name: 'BrainPage', description: 'Memoria Markdown persistente con cronologia di evidenze.', tags: ['memoria','markdown'] },
  autopub: { name: 'AutoPub', description: 'Fabbrica di contenuti autonoma: esegue il ciclo F1-F4 in modo autonomo.', tags: ['autopub','contenuto'] },
  security: { name: 'Sicurezza', description: 'Scanner di segreti e configurazioni di rischio in testo o repository.', tags: ['sicurezza','segreti'] },
  codequality: { name: 'Qualita del codice', description: 'Linter di code smells comuni: debugger, eval, any, console.log.', tags: ['qualita','linter'] },
  deps: { name: 'Dipendenze', description: 'Audit di vulnerabilita (SCA) con npm audit.', tags: ['dipendenze','cve'] },
  geometry: { name: 'Geometria parametrica', description: 'Geometria procedurale (superformula di Gielis): mesh ed export glTF o OBJ.', tags: ['geometria','glTF'] },
  pngrender: { name: 'PNG Render', description: 'Renderizzatore PNG in TypeScript puro: immagini da funzioni matematiche.', tags: ['png','render'] },
  procvid: { name: 'Procedural Video', description: 'Video procedurale deterministico: animazioni e montaggio ffmpeg o GIF.', tags: ['video','procedurale'] },
  physics2d: { name: 'Fisica 2D', description: 'Fisica 2D deterministica (Verlet e corpi rigidi) con canvas.', tags: ['fisica','2d'] },
  cadgeo: { name: 'CAD Geometry', description: 'Toolkit di geometria computazionale: Delaunay, Voronoi, BVH, B-spline.', tags: ['geometria','cad'] },
  evo: { name: 'Evolutivo', description: 'Algoritmo genetico deterministico riproducibile (xorshift32).', tags: ['genetico','ottimizzazione'] },
  evolution: { name: 'Evoluzione', description: 'Motore di evoluzione di artefatti con memoria persistente.', tags: ['evoluzione','artefatti'] },
  studio: { name: 'Studio', description: 'Hub dei media: salva, riproduci e deriva asset generati.', tags: ['studio','media'] },
  netwatch: { name: 'NetWatch', description: 'Sorvegliante di rete WiFi: monitora e riconnette la connessione.', tags: ['rete','wifi'] },
  designcompose: { name: 'Design Compose', description: 'Composizione 2D o 3D deterministica e senza chiavi da matematica.', tags: ['design','composizione'] },
  learnModels: { name: 'Modelli di apprendimento', description: 'Apprendimento programmato: pensieri, compressione della memoria e meta-ragionamento.', tags: ['apprendimento','meta'] },
};
export const DE: Partial<Record<Capability, LocalizedTool>> = {
  calculator: { name: 'Taschenrechner', description: 'Wertet einen mathematischen Ausdruck sicher aus (nur Mathematik).', tags: ['mathematik','berechnung'] },
  web: { name: 'Web', description: 'Liest Text und Metadaten einer oeffentlichen Seite (Web oder oeffentlicher Social-Beitrag). Ohne Schluessel.', tags: ['web','lesen'] },
  image: { name: 'Bild', description: 'Erzeugt ein fotorealistisches Bild aus einem Text mit einem kostenlosen Modell ohne Schluessel. Gibt eine URL zurueck.', tags: ['bild','generierung'] },
  video: { name: 'Video', description: 'Erstellt ein Video-Storyboard (Bildfolge) aus einem Text. Ohne Schluessel; echtes Video falls Anbieter vorhanden.', tags: ['video','storyboard'] },
  music: { name: 'Musik', description: 'Komponiert ein originales Musikstueck aus einem Text. Ohne Schluessel; echtes Audio falls Anbieter vorhanden.', tags: ['musik','komposition'] },
  design: { name: 'UI-Design', description: 'Erzeugt einen hochwertigen UI-Bildschirm aus einem Text mit Google Stitch (Google Labs kostenlos).', tags: ['design','ui'] },
  reach: { name: 'Web-Reichweite', description: 'Echtzeit-Internetzugriff: liest Seiten, sucht, durchsucht GitHub, parst RSS und YouTube-Metadaten.', tags: ['web','suche'] },
  skills: { name: 'Faehigkeiten', description: 'Fuehrt einen Schritt der Agenten-Entwicklungspipeline aus: plan, build, test, review, ship, simplify.', tags: ['agenten','pipeline'] },
  content: { name: 'Inhaltsressourcen', description: 'Kostenlose Assets fuer Video und Audio: Musik und Effekte (Tunetank) und Stock (mixkit).', tags: ['inhalt','assets'] },
  g0dm0d3: { name: 'G0DM0D3', description: 'Auswertung und Tests im G0DM0D3-Stil: Eingabestoerung, adaptive Stichproben und Mehrwinkel-Bewertung.', tags: ['auswertung','tests'] },
  topics: { name: 'Themen', description: 'Ideenmotor fuer Inhalte (AutoPub F1): priorisierte Briefs aus RSS und DuckDuckGo.', tags: ['inhalt','ideen'] },
  present: { name: 'Praesentation', description: 'Publikations-Builder (AutoPub F3): Paket pro Kanal mit Captions, Hashtags, Visuals und Zeitplan.', tags: ['publikation','paket'] },
  publish: { name: 'Veroeffentlichen', description: 'Verteilungs-Adapter (AutoPub F4): YouTube, TikTok, X, Meta, Telegram, Discord, Slack, LinkedIn.', tags: ['verteilung','kanaele'] },
  publications: { name: 'Publikations-Warteschlange', description: 'Verwaltung der Publikations-Warteschlange (AutoPub F4): anlegen, genehmigen, ablehnen und Geplantes veroeffentlichen.', tags: ['warteschlange','publikation'] },
  contenido: { name: 'Inhalt', description: 'Inhalts-Router (AutoPub F2): von Brief zu Post oder Video-Storyboard mit manifest.json.', tags: ['inhalt','storyboard'] },
  metrics: { name: 'Kennzahlen', description: 'KPIs pro Kanal und Feedback-Signale, um den Inhaltskreislauf zu schliessen.', tags: ['kennzahlen','analytics'] },
  memory: { name: 'Speicher', description: 'Archivsystem des Agenten-Speichers: merkt sich und liest, was der Nutzer zwischen Sitzungen erzaehlt.', tags: ['speicher','persistenz'] },
  diagram: { name: 'Diagramme', description: 'In sich geschlossene Editorial-Diagramme (timeline, data-flow, architecture, loop) in Dark Obsidian.', tags: ['diagramm','visualisierung'] },
  video_edit: { name: 'Video-Bearbeitung', description: 'Bearbeitungs-Pipeline: Transkription, EDL, ffmpeg-Render und deterministische Selbstbewertung.', tags: ['video','bearbeitung'] },
  screenflow: { name: 'ScreenFlow', description: 'Automatisierung der Bildschirmaufnahme: Plan, Erfassung, Bearbeitung und lokale Veroeffentlichung.', tags: ['bildschirm','automatisierung'] },
  cloud: { name: 'Cloud', description: 'Projekt-Cloud-Speicher: lokal oder Cloudflare R2, mit Pfad- und Groessenvalidierung.', tags: ['cloud','speicher'] },
  harness: { name: 'Harness', description: 'Plugin-Runtime fuer Agenten: startet, fuehrt aus und stoppt einen deterministischen Plugin-Baum.', tags: ['plugins','runtime'] },
  growth: { name: 'Wachstum', description: 'Kanal-Wachstumsmotor: Profil, A/B-Experimente und Playbook, das Siege ansammelt.', tags: ['wachstum','youtube'] },
  vfx: { name: 'VFX', description: 'Postproduktions-Planer (reframe, upscale, LUT, Rotoscopie, B-roll) deterministisch.', tags: ['vfx','postproduktion'] },
  codevfx: { name: 'CodeVFX', description: 'Visuelle Effekte zu 100 Prozent Code (ohne Assets): Feuer, Eis, Blitz, mit GLSL und Physik.', tags: ['effekte','code'] },
  recordly: { name: 'Recordly', description: 'ScreenFlow-Studio-Planer: Auto-Zoom, Cursor-Presets, Webcam-Bubble und MP4-Export.', tags: ['screenflow','demo'] },
  cerebro: { name: 'Cerebro', description: 'Autonomes Gehirn von UltraIa: lernt, erstellt, veroeffentlicht und berichtet in einem geplanten Zyklus.', tags: ['autonom','zyklus'] },
  travel: { name: 'Reisevideo', description: 'Reisevideo-Motor: 9:16-Plan aus einem Ziel mit zweisprachiger Erzaehlung und ffmpeg-Render.', tags: ['reisen','video'] },
  generative: { name: 'Generativ', description: 'Prozeduraler Medienmotor zu 100 Prozent Code: Bilder, Video und Audio aus Mathematik.', tags: ['prozedural','medien'] },
  research: { name: 'Recherche', description: 'Recherche-Motor: arXiv, GitHub, Live-Web und Extraktion von URLs als Text.', tags: ['recherche','wissen'] },
  enlaces: { name: 'Links', description: 'Link-Kuration: laedt geteilte Quellen des Projekts herunter und bindet sie ein.', tags: ['links','quellen'] },
  libros: { name: 'Buecher', description: 'Katalog von 115 kostenlosen Programmierbuechern und -tutorials auf Spanisch.', tags: ['buecher','lernen'] },
  sdf: { name: 'SDF', description: 'Signierte Distanzfelder und Ray Marching zu 100 Prozent Code: 3D-Szenen und GLSL.', tags: ['3d','raymarching'] },
  geom: { name: 'Geometrie', description: 'Geometrie- und Mathematikbibliothek: Vektoren, Matrizen, Meshes und SVG.', tags: ['geometrie','mathematik'] },
  videoqa: { name: 'VideoQA', description: 'Videoguete-Metriken: PSNR, SSIM, optischer Fluss und Urteil PASS oder FAIL.', tags: ['guete','video'] },
  motion: { name: 'Motion', description: 'Videobewegungsanalyse: optisches Flussfeld und Zerlegung Kamera oder Szene.', tags: ['bewegung','analyse'] },
  replica: { name: 'Replica', description: 'Analyse-durch-Synthese-Orchestrator: repliziert ein Ziel, indem er es erzeugt und vergleicht.', tags: ['replica','synthese'] },
  imaging: { name: 'Imaging', description: 'Bildverarbeitungs-Kernels in purem TypeScript: Filter, Kanten, optischer Fluss.', tags: ['bild','verarbeitung'] },
  creativo: { name: 'Kreativ', description: 'Kreativer Physikmotor zu 100 Prozent Code: 2D-Partikel, Ton und Canvas.', tags: ['physik','kreativ'] },
  semantic_memory: { name: 'Semantisches Gedaechtnis', description: 'Semantische Suche ueber verifiziertes Wissen mit Hashing und Kosinus.', tags: ['gedaechtnis','semantik'] },
  autolearn: { name: 'Auto-Lernen', description: 'Autoprogrammierungs-Agent: erkennt Luecken und erzeugt den Verbesserungsplan.', tags: ['lernen','automatisierung'] },
  genesis: { name: 'Genesis', description: 'Autonomer Engineering-Motor: validiert das Manifest und waehlt die naechste Aktion.', tags: ['engineering','autonom'] },
  vault: { name: 'Tresor', description: 'Eigenes Repository: speichert Daten, Dateien, Kreationen und Beweise des Projekts.', tags: ['tresor','speicher'] },
  pdfsearch: { name: 'PDF Search', description: 'PDF-Suche: OpenAlex und DuckDuckGo filetype:pdf in den Tresor uebertragen.', tags: ['pdf','suche'] },
  qdrant_memory: { name: 'Qdrant-Speicher', description: 'Externer persistenter Speicher in Qdrant fuer das Korpus verifizierter Wahrheit.', tags: ['speicher','persistenz'] },
  kgraph: { name: 'Knowledge Graph', description: 'Wissensgraphen-Builder aus Code und Dokumenten.', tags: ['graph','wissen'] },
  brainpage: { name: 'BrainPage', description: 'Persistente Markdown-Erinnerung mit Evidenz-Zeitstrahl.', tags: ['gedaechtnis','markdown'] },
  autopub: { name: 'AutoPub', description: 'Autonome Inhaltsfabrik: fuehrt den Zyklus F1-F4 autonom aus.', tags: ['autopub','inhalt'] },
  security: { name: 'Sicherheit', description: 'Scanner fuer Geheimnisse und Risikokonfigurationen in Text oder Repository.', tags: ['sicherheit','geheimnisse'] },
  codequality: { name: 'Code-Qualitaet', description: 'Linter fuer gaengige Code Smells: debugger, eval, any, console.log.', tags: ['qualitaet','linter'] },
  deps: { name: 'Abhaengigkeiten', description: 'Schwachstellen-Audit (SCA) mit npm audit.', tags: ['abhaengigkeiten','cve'] },
  geometry: { name: 'Parametrische Geometrie', description: 'Prozedurale Geometrie (Gielis-Superformel): Meshes und Export glTF oder OBJ.', tags: ['geometrie','glTF'] },
  pngrender: { name: 'PNG Render', description: 'PNG-Renderer in purem TypeScript: Bilder aus mathematischen Funktionen.', tags: ['png','render'] },
  procvid: { name: 'Procedural Video', description: 'Deterministisches prozedurales Video: Animationen und ffmpeg- oder GIF-Montage.', tags: ['video','prozedural'] },
  physics2d: { name: '2D-Physik', description: 'Deterministische 2D-Physik (Verlet und starre Koerper) mit Canvas.', tags: ['physik','2d'] },
  cadgeo: { name: 'CAD Geometry', description: 'Computergeometrie-Toolkit: Delaunay, Voronoi, BVH, B-spline.', tags: ['geometrie','cad'] },
  evo: { name: 'Evolutionaer', description: 'Deterministischer reproduzierbarer genetischer Algorithmus (xorshift32).', tags: ['genetisch','optimierung'] },
  evolution: { name: 'Evolution', description: 'Evolutionsmotor fuer Artefakte mit persistentem Gedaechtnis.', tags: ['evolution','artefakte'] },
  studio: { name: 'Studio', description: 'Medien-Hub: speichert, spielt und leitet generierte Assets ab.', tags: ['studio','medien'] },
  netwatch: { name: 'NetWatch', description: 'WLAN-Netzwerkwaechter: ueberwacht und verbindet die Verbindung neu.', tags: ['netz','wifi'] },
  designcompose: { name: 'Design Compose', description: 'Deterministische und schluessellose 2D- oder 3D-Komposition aus Mathematik.', tags: ['design','komposition'] },
  learnModels: { name: 'Lernmodelle', description: 'Programmiertes Lernen: Gedanken, Gedaechtniskompression und Meta-Reasoning.', tags: ['lernen','meta'] },
};
export const ZH: Partial<Record<Capability, LocalizedTool>> = {
  calculator: { name: '计算器', description: '安全地计算数学表达式（仅数学）。', tags: ['数学','计算'] },
  web: { name: '网页', description: '读取公开页面的文本和元数据（网页或公开社交帖子）。无需密钥。', tags: ['网页','读取'] },
  image: { name: '图像', description: '用免费无密钥模型从文本生成写实图像。返回 URL。', tags: ['图像','生成'] },
  video: { name: '视频', description: '从文本生成视频分镜（帧序列）。无需密钥；如有提供商则生成真实视频。', tags: ['视频','分镜'] },
  music: { name: '音乐', description: '从文本创作原创音乐。无需密钥；如有提供商则生成真实音频。', tags: ['音乐','作曲'] },
  design: { name: 'UI 设计', description: '用 Google Stitch（Google Labs 免费）从文本生成高保真 UI 界面。', tags: ['设计','ui'] },
  reach: { name: '网络触达', description: '实时联网：读取页面、搜索、搜索 GitHub、解析 RSS 与 YouTube 元数据。', tags: ['网页','搜索'] },
  skills: { name: '技能', description: '执行智能体开发流水线的步骤：plan、build、test、review、ship、simplify。', tags: ['智能体','流水线'] },
  content: { name: '内容资源', description: '视频与音频的免费素材：音乐与音效（Tunetank）和库存（mixkit）。', tags: ['内容','素材'] },
  g0dm0d3: { name: 'G0DM0D3', description: 'G0DM0D3 风格的评估与测试：输入扰动、自适应采样与多角度评估。', tags: ['评估','测试'] },
  topics: { name: '主题', description: '内容创意引擎（AutoPub F1）：来自 RSS 和 DuckDuckGo 的优先简报。', tags: ['内容','创意'] },
  present: { name: '发布稿', description: '发布构建器（AutoPub F3）：按渠道打包字幕、标签、视觉与时间表。', tags: ['发布','打包'] },
  publish: { name: '发布', description: '分发适配器（AutoPub F4）：YouTube、TikTok、X、Meta、Telegram、Discord、Slack、LinkedIn。', tags: ['分发','渠道'] },
  publications: { name: '发布队列', description: '发布队列管理（AutoPub F4）：创建、批准、拒绝与发布已排程内容。', tags: ['队列','发布'] },
  contenido: { name: '内容', description: '内容路由器（AutoPub F2）：从简报到帖子或视频分镜，含 manifest.json。', tags: ['内容','分镜'] },
  metrics: { name: '指标', description: '按渠道的 KPI 与反馈信号，用于闭环内容。', tags: ['指标','分析'] },
  memory: { name: '记忆', description: '智能体记忆存档系统：记住并读取用户在会话间讲述的内容。', tags: ['记忆','持久化'] },
  diagram: { name: '图表', description: '自包含编辑图表（时间线、数据流、架构、循环），采用 Dark Obsidian 风格。', tags: ['图表','可视化'] },
  video_edit: { name: '视频编辑', description: '编辑流水线：转录、EDL、ffmpeg 渲染与确定性自评估。', tags: ['视频','编辑'] },
  screenflow: { name: 'ScreenFlow', description: '屏幕录制自动化：计划、捕获、编辑与本地发布。', tags: ['屏幕','自动化'] },
  cloud: { name: '云端', description: '项目云存储：本地或 Cloudflare R2，含路径与大小校验。', tags: ['云','存储'] },
  harness: { name: 'Harness', description: '智能体插件运行时：启动、执行并停止确定性插件树。', tags: ['插件','运行时'] },
  growth: { name: '增长', description: '渠道增长引擎：画像、A/B 实验与累积胜利的手册。', tags: ['增长','youtube'] },
  vfx: { name: 'VFX', description: '后期制作规划器（reframe、upscale、LUT、转描、B-roll），确定性。', tags: ['vfx','后期'] },
  codevfx: { name: 'CodeVFX', description: '100% 代码视觉效果（无素材）：火、冰、闪电，使用 GLSL 与物理。', tags: ['特效','代码'] },
  recordly: { name: 'Recordly', description: 'ScreenFlow Studio 规划器：自动缩放、光标预设、摄像头气泡与 MP4 导出。', tags: ['screenflow','演示'] },
  cerebro: { name: 'Cerebro', description: 'UltraIa 自主大脑：在计划周期内学习、创建、发布与汇报。', tags: ['自主','周期'] },
  travel: { name: '旅行视频', description: '旅行视频引擎：从目的地生成 9:16 方案，含双语旁白与 ffmpeg 渲染。', tags: ['旅行','视频'] },
  generative: { name: '生成式', description: '100% 代码程序化媒体引擎：从数学生成图像、视频与音频。', tags: ['程序化','媒体'] },
  research: { name: '研究', description: '研究引擎：arXiv、GitHub、实时网络与 URL 提取为文本。', tags: ['研究','知识'] },
  enlaces: { name: '链接', description: '链接策展：下载并调用项目共享的来源。', tags: ['链接','来源'] },
  libros: { name: '书籍', description: '115 本免费编程书籍与教程目录（西班牙语）。', tags: ['书籍','学习'] },
  sdf: { name: 'SDF', description: '100% 代码符号距离场与光线步进：3D 场景与 GLSL。', tags: ['3d','光线步进'] },
  geom: { name: '几何', description: '几何与数学库：向量、矩阵、网格与 SVG。', tags: ['几何','数学'] },
  videoqa: { name: 'VideoQA', description: '视频质量指标：PSNR、SSIM、光流与 PASS/FAIL 判定。', tags: ['质量','视频'] },
  motion: { name: 'Motion', description: '视频运动分析：光流场与相机或场景分解。', tags: ['运动','分析'] },
  replica: { name: 'Replica', description: '分析即合成编排器：通过生成并比较来复现目标。', tags: ['复现','合成'] },
  imaging: { name: 'Imaging', description: '纯 TypeScript 图像处理内核：滤波、边缘、光流。', tags: ['图像','处理'] },
  creativo: { name: '创意', description: '100% 代码创意物理引擎：2D 粒子、声音与画布。', tags: ['物理','创意'] },
  semantic_memory: { name: '语义记忆', description: '基于哈希与余弦的已验证知识语义检索。', tags: ['记忆','语义'] },
  autolearn: { name: '自动学习', description: '自动编程智能体：发现缺口并生成改进计划。', tags: ['学习','自动化'] },
  genesis: { name: 'Genesis', description: '自主工程引擎：校验清单并选择下一步动作。', tags: ['工程','自主'] },
  vault: { name: '保险库', description: '自有仓库：保存项目的数据、文件、创作与证据。', tags: ['保险库','存储'] },
  pdfsearch: { name: 'PDF 搜索', description: 'PDF 搜索：OpenAlex 与 DuckDuckGo filetype:pdf 导入保险库。', tags: ['pdf','搜索'] },
  qdrant_memory: { name: 'Qdrant 记忆', description: 'Qdrant 外部持久记忆，用于已验证真相语料。', tags: ['记忆','持久化'] },
  kgraph: { name: '知识图谱', description: '从代码与文档构建知识图谱。', tags: ['图谱','知识'] },
  brainpage: { name: 'BrainPage', description: '带证据时间线的持久 Markdown 记忆。', tags: ['记忆','markdown'] },
  autopub: { name: 'AutoPub', description: '自主内容工厂：自主运行 F1-F4 循环。', tags: ['autopub','内容'] },
  security: { name: '安全', description: '文本或仓库中的密钥与风险配置扫描器。', tags: ['安全','密钥'] },
  codequality: { name: '代码质量', description: '常见代码异味检查：debugger、eval、any、console.log。', tags: ['质量','linter'] },
  deps: { name: '依赖', description: '漏洞审计（SCA），使用 npm audit。', tags: ['依赖','cve'] },
  geometry: { name: '参数化几何', description: '程序化几何（Gielis 超公式）：网格与 glTF 或 OBJ 导出。', tags: ['几何','glTF'] },
  pngrender: { name: 'PNG 渲染', description: '纯 TypeScript PNG 渲染器：从数学函数生成图像。', tags: ['png','渲染'] },
  procvid: { name: '程序化视频', description: '确定性程序化视频：动画与 ffmpeg 或 GIF 拼接。', tags: ['视频','程序化'] },
  physics2d: { name: '2D 物理', description: '确定性 2D 物理（Verlet 与刚体），使用画布。', tags: ['物理','2d'] },
  cadgeo: { name: 'CAD 几何', description: '计算几何工具包：Delaunay、Voronoi、BVH、B 样条。', tags: ['几何','cad'] },
  evo: { name: '进化', description: '确定性可复现遗传算法（xorshift32）。', tags: ['遗传','优化'] },
  evolution: { name: '演化', description: '带持久记忆的制品演化引擎。', tags: ['演化','制品'] },
  studio: { name: '工作室', description: '媒体中心：保存、播放与派生生成资源。', tags: ['工作室','媒体'] },
  netwatch: { name: 'NetWatch', description: 'WiFi 网络监视器：监控并重新连接。', tags: ['网络','wifi'] },
  designcompose: { name: 'Design Compose', description: '确定性且无密钥的 2D 或 3D 合成，来自数学。', tags: ['设计','合成'] },
  learnModels: { name: '学习模型', description: '编程式学习：思考、记忆压缩与元推理。', tags: ['学习','元'] },
};
export const RU: Partial<Record<Capability, LocalizedTool>> = {
  calculator: { name: 'Калькулятор', description: 'Безопасно вычисляет математическое выражение (только математика).', tags: ['математика','вычисления'] },
  web: { name: 'Веб', description: 'Читает текст и метаданные публичной страницы (веб или публичный соцпост). Без ключей.', tags: ['веб','чтение'] },
  image: { name: 'Изображение', description: 'Генерирует фотореалистичное изображение из текста бесплатной моделью без ключей. Возвращает URL.', tags: ['изображение','генерация'] },
  video: { name: 'Видео', description: 'Создаёт раскадровку видео (последовательность кадров) из текста. Без ключей; настоящее видео при наличии провайдера.', tags: ['видео','раскадровка'] },
  music: { name: 'Музыка', description: 'Сочиняет оригинальное музыкальное произведение из текста. Без ключей; настоящее аудио при наличии провайдера.', tags: ['музыка','композиция'] },
  design: { name: 'UI-дизайн', description: 'Генерирует экран UI высокой точности из текста с помощью Google Stitch (Google Labs бесплатно).', tags: ['дизайн','ui'] },
  reach: { name: 'Веб-охват', description: 'Доступ в интернет в реальном времени: читает страницы, ищет, ищет на GitHub, парсит RSS и метаданные YouTube.', tags: ['веб','поиск'] },
  skills: { name: 'Навыки', description: 'Выполняет шаг конвейера разработки агентов: plan, build, test, review, ship, simplify.', tags: ['агенты','конвейер'] },
  content: { name: 'Контент-ресурсы', description: 'Бесплатные ассеты для видео и аудио: музыка и эффекты (Tunetank) и сток (mixkit).', tags: ['контент','ассеты'] },
  g0dm0d3: { name: 'G0DM0D3', description: 'Оценка и тесты в стиле G0DM0D3: возмущение входа, адаптивная выборка и многоугольная оценка.', tags: ['оценка','тесты'] },
  topics: { name: 'Темы', description: 'Движок идей контента (AutoPub F1): приоритетные брифы из RSS и DuckDuckGo.', tags: ['контент','идеи'] },
  present: { name: 'Презентация', description: 'Конструктор публикаций (AutoPub F3): пакет по каналу с подписями, хештегами, визуалом и расписанием.', tags: ['публикация','пакет'] },
  publish: { name: 'Опубликовать', description: 'Адаптеры распространения (AutoPub F4): YouTube, TikTok, X, Meta, Telegram, Discord, Slack, LinkedIn.', tags: ['распространение','каналы'] },
  publications: { name: 'Очередь публикаций', description: 'Управление очередью публикаций (AutoPub F4): создать, одобрить, отклонить и опубликовать запланированное.', tags: ['очередь','публикация'] },
  contenido: { name: 'Контент', description: 'Маршрутизатор контента (AutoPub F2): от брифа к посту или раскадровке видео с manifest.json.', tags: ['контент','раскадровка'] },
  metrics: { name: 'Метрики', description: 'KPI по каналам и сигналы обратной связи для замыкания цикла контента.', tags: ['метрики','аналитика'] },
  memory: { name: 'Память', description: 'Система архива памяти агента: помнит и читает то, что пользователь рассказывает между сессиями.', tags: ['память','сохранение'] },
  diagram: { name: 'Диаграммы', description: 'Автономные редакционные диаграммы (таймлайн, поток данных, архитектура, цикл) в стиле Dark Obsidian.', tags: ['диаграмма','визуализация'] },
  video_edit: { name: 'Монтаж видео', description: 'Конвейер монтажа: транскрипция, EDL, рендер ffmpeg и детерминированная самооценка.', tags: ['видео','монтаж'] },
  screenflow: { name: 'ScreenFlow', description: 'Автоматизация записи экрана: план, захват, монтаж и локальная публикация.', tags: ['экран','автоматизация'] },
  cloud: { name: 'Облако', description: 'Облачное хранилище проекта: локально или Cloudflare R2, с проверкой путей и размеров.', tags: ['облако','хранилище'] },
  harness: { name: 'Harness', description: 'Плагин-рантайм для агентов: запускает, выполняет и останавливает детерминированное дерево плагинов.', tags: ['плагины','рантайм'] },
  growth: { name: 'Рост', description: 'Движок роста канала: профиль, A/B-эксперименты и плейбук, накапливающий победы.', tags: ['рост','youtube'] },
  vfx: { name: 'VFX', description: 'Планировщик постпродакшена (reframe, upscale, LUT, ротоскопия, B-roll), детерминированный.', tags: ['vfx','постпродакшен'] },
  codevfx: { name: 'CodeVFX', description: 'Визуальные эффекты на 100 процентов кодом (без ассетов): огонь, лёд, молния, с GLSL и физикой.', tags: ['эффекты','код'] },
  recordly: { name: 'Recordly', description: 'Планировщик ScreenFlow Studio: авто-зум, пресеты курсора, пузырь веб-камеры и экспорт MP4.', tags: ['screenflow','демо'] },
  cerebro: { name: 'Cerebro', description: 'Автономный мозг UltraIa: учится, создаёт, публикует и отчитывается в плановом цикле.', tags: ['автономный','цикл'] },
  travel: { name: 'Видео путешествий', description: 'Движок видео путешествий: план 9:16 из пункта назначения с двуязычным закадровым и рендером ffmpeg.', tags: ['путешествия','видео'] },
  generative: { name: 'Генеративное', description: 'Процедурный медиа-движок на 100 процентов кодом: изображения, видео и аудио из математики.', tags: ['процедурное','медиа'] },
  research: { name: 'Исследование', description: 'Поисковый движок: arXiv, GitHub, живой веб и извлечение URL как текста.', tags: ['исследование','знание'] },
  enlaces: { name: 'Ссылки', description: 'Курация ссылок: загружает и вовлекает общие источники проекта.', tags: ['ссылки','источники'] },
  libros: { name: 'Книги', description: 'Каталог из 115 бесплатных книг и учебников по программированию на испанском.', tags: ['книги','обучение'] },
  sdf: { name: 'SDF', description: 'Подписанные поля расстояний и рей-марчинг на 100 процентов кодом: 3D-сцены и GLSL.', tags: ['3d','реймарчинг'] },
  geom: { name: 'Геометрия', description: 'Библиотека геометрии и математики: векторы, матрицы, сетки и SVG.', tags: ['геометрия','математика'] },
  videoqa: { name: 'VideoQA', description: 'Метрики качества видео: PSNR, SSIM, оптический поток и вердикт PASS или FAIL.', tags: ['качество','видео'] },
  motion: { name: 'Motion', description: 'Анализ движения видео: поле оптического потока и разложение камеры или сцены.', tags: ['движение','анализ'] },
  replica: { name: 'Replica', description: 'Оркестратор анализ-через-синтез: воспроизводит цель, генерируя её и сравнивая.', tags: ['реплика','синтез'] },
  imaging: { name: 'Imaging', description: 'Ядра обработки изображений на чистом TypeScript: фильтры, края, оптический поток.', tags: ['изображение','обработка'] },
  creativo: { name: 'Креатив', description: 'Творческий физический движок на 100 процентов кодом: 2D-частицы, звук и холст.', tags: ['физика','креатив'] },
  semantic_memory: { name: 'Семантическая память', description: 'Семантический поиск по проверенным знаниям с хешированием и косинусом.', tags: ['память','семантика'] },
  autolearn: { name: 'Автообучение', description: 'Агент автопрограммирования: находит пробелы и генерирует план улучшения.', tags: ['обучение','автоматизация'] },
  genesis: { name: 'Genesis', description: 'Автономный инженерный движок: валидирует манифест и выбирает следующее действие.', tags: ['инженерия','автономный'] },
  vault: { name: 'Хранилище', description: 'Собственный репозиторий: сохраняет данные, файлы, творения и доказательства проекта.', tags: ['хранилище','сохранение'] },
  pdfsearch: { name: 'PDF Search', description: 'Поиск PDF: OpenAlex и DuckDuckGo filetype:pdf переносятся в хранилище.', tags: ['pdf','поиск'] },
  qdrant_memory: { name: 'Память Qdrant', description: 'Внешняя постоянная память в Qdrant для корпуса проверенной истины.', tags: ['память','сохранение'] },
  kgraph: { name: 'Knowledge Graph', description: 'Конструктор графа знаний из кода и документов.', tags: ['граф','знание'] },
  brainpage: { name: 'BrainPage', description: 'Постоянная Markdown-память с временной шкалой доказательств.', tags: ['память','markdown'] },
  autopub: { name: 'AutoPub', description: 'Автономная фабрика контента: выполняет цикл F1-F4 автономно.', tags: ['autopub','контент'] },
  security: { name: 'Безопасность', description: 'Сканер секретов и рисковых конфигураций в тексте или репозитории.', tags: ['безопасность','секреты'] },
  codequality: { name: 'Качество кода', description: 'Линтер частых code smells: debugger, eval, any, console.log.', tags: ['качество','линтер'] },
  deps: { name: 'Зависимости', description: 'Аудит уязвимостей (SCA) с помощью npm audit.', tags: ['зависимости','cve'] },
  geometry: { name: 'Параметрическая геометрия', description: 'Процедурная геометрия (суперформула Гилиса): сетки и экспорт glTF или OBJ.', tags: ['геометрия','glTF'] },
  pngrender: { name: 'PNG Render', description: 'PNG-рендерер на чистом TypeScript: изображения из математических функций.', tags: ['png','рендер'] },
  procvid: { name: 'Procedural Video', description: 'Детерминированное процедурное видео: анимации и сборка ffmpeg или GIF.', tags: ['видео','процедурное'] },
  physics2d: { name: '2D-физика', description: 'Детерминированная 2D-физика (Верле и твёрдые тела) с холстом.', tags: ['физика','2d'] },
  cadgeo: { name: 'CAD Geometry', description: 'Набор вычислительной геометрии: Delaunay, Voronoi, BVH, B-сплайн.', tags: ['геометрия','cad'] },
  evo: { name: 'Эволюционный', description: 'Детерминированный воспроизводимый генетический алгоритм (xorshift32).', tags: ['генетический','оптимизация'] },
  evolution: { name: 'Эволюция', description: 'Движок эволюции артефактов с постоянной памятью.', tags: ['эволюция','артефакты'] },
  studio: { name: 'Studio', description: 'Медиа-хаб: сохраняет, воспроизводит и порождает сгенерированные ассеты.', tags: ['студия','медиа'] },
  netwatch: { name: 'NetWatch', description: 'Сторож сети WiFi: мониторит и переподключает соединение.', tags: ['сеть','wifi'] },
  designcompose: { name: 'Design Compose', description: 'Детерминированная и безключевая 2D- или 3D-композиция из математики.', tags: ['дизайн','композиция'] },
  learnModels: { name: 'Модели обучения', description: 'Программируемое обучение: мысли, сжатие памяти и метарассуждение.', tags: ['обучение','мета'] },
};

function titleCase(id: string): string {
  return id.replace(/[_-]/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getToolCatalog(locale: CatalogLocale = 'es'): ToolCatalogEntry[] {
  const ids = Object.keys(TOOL_DESCRIPTIONS) as Capability[];
  const maps: Record<string, Partial<Record<Capability, LocalizedTool>>> = { es: ES, pt: PT, it: IT, de: DE, zh: ZH, ru: RU };
  return ids.map((id) => {
    const meta = CATALOG_META[id];
    const i18n: Partial<Record<CatalogLocale, LocalizedTool>> = {};
    i18n.en = { name: titleCase(id), description: TOOL_DESCRIPTIONS[id] ?? id, tags: [] };
    for (const loc of ['es','pt','it','de','zh','ru'] as CatalogLocale[]) {
      const m = maps[loc];
      if (m && m[id]) i18n[loc] = m[id];
    }
    return { id, category: meta.category, route: meta.route, related: meta.related, consolidates: meta.consolidates, i18n };
  });
}

export function localizeEntry(entry: ToolCatalogEntry, locale: CatalogLocale): { name: string; description: string; tags: string[]; fallback: boolean } {
  const direct = entry.i18n[locale];
  if (direct) return { ...direct, fallback: false };
  if (entry.i18n.en) return { ...entry.i18n.en, fallback: locale !== 'en' };
  if (entry.i18n.es) return { ...entry.i18n.es, fallback: true };
  return { name: entry.id, description: entry.id, tags: [], fallback: true };
}
