#!/usr/bin/env python3
"""
Export Instagram cookies from browser for use with gallery-dl or yt-dlp.
Supports Chrome, Edge, Firefox.
"""

import browser_cookie3
import sys
import os

def export_cookies(browser_name, domain="instagram.com", output_file="cookies.txt"):
    """Export cookies for a specific domain from the specified browser."""
    
    browser_funcs = {
        "chrome": browser_cookie3.chrome,
        "edge": browser_cookie3.edge,
        "firefox": browser_cookie3.firefox,
    }
    
    if browser_name not in browser_funcs:
        print(f"Unsupported browser: {browser_name}")
        print(f"Supported: {list(browser_funcs.keys())}")
        return False
    
    try:
        print(f"Loading cookies from {browser_name}...")
        cookies = browser_funcs[browser_name](domain_name=domain)
        
        cookie_list = list(cookies)
        if not cookie_list:
            print(f"No cookies found for {domain} in {browser_name}")
            return False
        
        # Write in Netscape format (compatible with yt-dlp and gallery-dl)
        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file was generated by export_instagram_cookies.py\n\n")
            
            for cookie in cookie_list:
                # Netscape format: domain, domain_specified, path, secure, expires, name, value
                domain_specified = "TRUE" if cookie.domain.startswith(".") else "FALSE"
                secure = "TRUE" if cookie.secure else "FALSE"
                expires = str(int(cookie.expires)) if cookie.expires else "0"
                
                f.write(f"{cookie.domain}\t{domain_specified}\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n")
        
        print(f"Exported {len(cookie_list)} cookies to {output_file}")
        return True
        
    except Exception as e:
        print(f"Error exporting cookies from {browser_name}: {e}")
        return False

def main():
    # Try browsers in order of preference
    browsers = ["chrome", "edge", "firefox"]
    output_file = "cookies.txt"
    
    # Allow override via command line
    if len(sys.argv) > 1:
        output_file = sys.argv[1]
    if len(sys.argv) > 2:
        browsers = [sys.argv[2]]
    
    for browser in browsers:
        print(f"\nTrying {browser}...")
        if export_cookies(browser, "instagram.com", output_file):
            print(f"\nSuccess! Cookies saved to {output_file}")
            print(f"You can now use:")
            print(f"  gallery-dl --cookies {output_file} <instagram_url>")
            print(f"  yt-dlp --cookies {output_file} <instagram_url>")
            return 0
    
    print("\nFailed to export cookies from any browser.")
    print("Make sure you are logged into Instagram in at least one browser.")
    return 1

if __name__ == "__main__":
    sys.exit(main())